03/30/2011 00:07:02: Using keywords 
/Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/connection.rb:788:in `rescue in send_message_on_socket': Operation failed with the following exception: closed stream (Mongo::ConnectionFailure)
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/connection.rb:775:in `send_message_on_socket'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/connection.rb:434:in `block in receive_message'
	from <internal:prelude>:10:in `synchronize'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/connection.rb:433:in `receive_message'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/cursor.rb:384:in `block in send_initial_query'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/connection.rb:543:in `instrument'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/cursor.rb:383:in `send_initial_query'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/cursor.rb:348:in `refresh'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/cursor.rb:72:in `next_document'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/db.rb:492:in `command'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/mongo-1.2.4/lib/mongo/cursor.rb:128:in `count'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/bundler/gems/mongoid-1fe9cc96b5a1/lib/mongoid/cursor.rb:37:in `block (3 levels) in <class:Cursor>'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/bundler/gems/mongoid-1fe9cc96b5a1/lib/mongoid/collections/retry.rb:29:in `retry_on_connection_failure'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/bundler/gems/mongoid-1fe9cc96b5a1/lib/mongoid/cursor.rb:36:in `block (2 levels) in <class:Cursor>'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/bundler/gems/mongoid-1fe9cc96b5a1/lib/mongoid/contexts/mongo.rb:74:in `count'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/bundler/gems/mongoid-1fe9cc96b5a1/lib/mongoid/criteria.rb:47:in `count'
	from script/tweet_engine:24:in `block (2 levels) in <class:TweetDjinn>'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base/dsl.rb:14:in `instance_exec'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base/dsl.rb:14:in `block (3 levels) in djinn'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base.rb:48:in `block in start'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base/tonic.rb:42:in `block in daemonize'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base/tonic.rb:13:in `fork'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base/tonic.rb:13:in `daemonize'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base.rb:44:in `start'
	from /Users/baphled/.rvm/gems/ruby-1.9.2-head/gems/djinn-0.1.7/lib/djinn/base/dsl.rb:29:in `djinnify'
	from script/tweet_engine:46:in `<main>'
IOError when attempting to close socket connected to localhost:27017: #<IOError: closed stream>
